
export const categoryConstants = {
  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",

  ADD_CATEGORY_REQUEST:"ADD_CATEGORY_REQUEST",
  ADD_CATEGORY_SUCCESS:"ADD_CATEGORY_SUCCESS",
  ADD_CATEGORY_FAILURE:"ADD_CATEGORY_FAILURE",
  
  DEL_CATEGORY_REQUEST:"DEL_CATEGORY_REQUEST",
  DEL_CATEGORY_SUCCESS:"DEL_CATEGORY_SUCCESS",
  DEL_CATEGORY_FAILURE:"DEL_CATEGORY_FAILURE",


  EDIT_CATEGORY_REQUEST:"EDIT_CATEGORY_REQUEST",
  EDIT_CATEGORY_SUCCESS:"EDIT_CATEGORY_SUCCESS",
  EDIT_CATEGORY_FAILURE:"EDIT_CATEGORY_FAILURE",


};

export const brandConstants ={
  GET_BRAND_REQUEST: "GET_BRAND_REQUEST",
  GET_BRAND_SUCCESS: "GET_BRAND_SUCCESS",
  GET_BRAND_FAILURE: "GET_BRAND_FAILURE",

}
export const productConstants = {
  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
};
